<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Sign_In_Account</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>9d82fca9-634a-4c4a-8a50-458fb73e92f8</testSuiteGuid>
   <testCaseLink>
      <guid>3aba8f54-2b08-451f-b70d-b62e8c32d285</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Data Type/Sign-In-Account</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>5e9465b9-7cc0-49cd-8f60-fb9af525c974</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/Sign_In_Account</testDataId>
      </testDataLink>
      <variableLink>
         <testDataLinkId>5e9465b9-7cc0-49cd-8f60-fb9af525c974</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>Username</value>
         <variableId>ae462a75-555b-49e9-b415-c25da7c92d83</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>5e9465b9-7cc0-49cd-8f60-fb9af525c974</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>Password</value>
         <variableId>197f3071-e2d1-4d39-82b8-16c7d553602d</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
